start-countdown-duration: 5
border-size: 20001
board-size: 5
bingo-item:
  material: KNOWLEDGE_BOOK
  name: "<!i><green>Bingo Book"
  lore:
    - "<!i><gray>Interact to open your bingo board"
    - "<!i><gray>Alternatively, you can just run <white>/bingo"
    - "<!i><gray>You can always get a new book by running <white>/bingo book"
advancement-options:
  - minecraft:story/mine_stone